Nuevo tipo de dato String
ericknavarro/InterpreteSencilloJisonJS pull request #14
Opened 2020-01-26 20:52 UTC by ronald1512

Esta es mi propuesta de mejora: Se agregó el nuevo tipo de dato String, con ello ahora se pueden hacer declaraciones de dicho tipo, así mismo asignaciones. También se tomaron en cuenta todas las validaciones correspondientes para que funcione de manera correcta. Lamento los últimos 2 pull request que cerré, lo hice porque no había seguido correctamente las instrucciones, por favor si cometí algún error, siéntete libre de hacerme una corrección, muchas gracias. Soy Ronald Romero 201701048 OLC2 sección B+

2020-01-27 14:12 UTC, rjanixz approved these changes

2020-02-12 04:15 UTC, rjanixz requested changes
@ronald1512 hemos comenzado a hacer merge de los pull request aprobados, lamentablemente con los cambios que ya fuero agregados al repositorio, tus cambios entran en conflictos, podrías por favor corregirlos?

Si tienes alguna duda no dudes en hacerme saber.

Saludos

2020-02-13 01:01 UTC, ronald1512 commented
Buenas Rainman, ya resolví los confilctos. Me cuentas cualquier cosa

2020-02-28 00:03 UTC, rjanixz commented
@ronald1512 perdona los inconvenientes, aún hay conflictos con el archivo gramatica.js.

Podes resolverlos por favor?

2020-03-03 15:39 UTC, closed without merging