Se ha agregado la sentencia de control FOR.
ericknavarro/InterpreteSencilloJisonJS pull request #15
Opened 2020-01-27 01:50 UTC by gpeitzner

Se ha creado una sentencia básica de control FOR. Tiene la siguiente estructura:

Para(Asignación; Expresión Lógica; Aumento){
Instrucciones*
}

Ejemplo:

`numero i; para(i=0; i < 10; i++){ /* Instrucciones */ }`

Por el momento funciona con una asignación y el aumento.

Saludos Cordiales. 

Guillermo Alfredo Peitzner Estrada - 201504468.

2020-01-27 14:12 UTC, rjanixz requested changes
Muy buena propuesta, podrías por favor subir únicamente los cambios necesarios, dejar los espacios y tabs como estaban originalmente, ya que esto podría causar conflicto con los compañeros que ya hicieron su fork.

Muchas gracias

2020-01-27 23:30 UTC, gpeitzner commented
Buenas tardes, ya realice los cambios requeridos. Utilice el código original sin cambiar la estructura, agregue el ciclo FOR y su respectivo ejemplo en el archivo de entrada. 

Saludos.

Guillermo Alfredo Peitzner Estrada - 201504468.

2020-01-29 04:29 UTC, rjanixz requested changes
aún tenes muchos espacios innecesarios en varios archivos

![image](https://user-images.githubusercontent.com/6462555/73327973-9638a180-421d-11ea-8f94-a9d322098d4f.png)

![image](https://user-images.githubusercontent.com/6462555/73327982-a2bcfa00-421d-11ea-9cc9-ed3ab3dd3caf.png)

Te pido que me ayudes a quitarlos para evitar conflicto con otros pull request.

Muchas gracias

2020-01-29 04:29 UTC, rjanixz commented on instrucciones.js
> +	NUMERO: 'VAL_NUMERO',
espacios innecesarios

2020-01-29 04:29 UTC, rjanixz commented on instrucciones.js
> +	SUMA: 'OP_SUMA',
modificación innecesaria de los espacios

2020-01-29 04:29 UTC, rjanixz commented on instrucciones.js
> +	MENOR_QUE: 'OP_MENOR_QUE',
modificación innecesaria de los espacios

2020-01-29 04:29 UTC, rjanixz commented on instrucciones.js
> +	ASIGNACION: 'INSTR_ASIGANCION',
modificación innecesaria de los espacios

2020-01-29 04:29 UTC, rjanixz commented on instrucciones.js
> -	nuevoOperacionBinaria: function(operandoIzq, operandoDer, tipo) {
Espaciosa innecesarios

2020-01-29 04:29 UTC, rjanixz commented on instrucciones.js
> +	nuevoOperacionUnaria: function (operando, tipo) {
Espaciosa innecesarios

2020-01-29 04:29 UTC, rjanixz commented on instrucciones.js
> +	nuevoValor: function (valor, tipo) {
Espaciosa innecesarios

2020-01-29 04:31 UTC, rjanixz commented
@gpeitzner gracias por los cambios, este pull request ya está listo

2020-01-29 04:31 UTC, rjanixz approved these changes

2020-01-29 22:34 UTC, gpeitzner commented
Gracias, cualquier inconveniente estoy a la orden.

Saludos.

2020-02-12 04:13 UTC, merged

2020-02-23 01:04 UTC, ericknavarro commented
Muchas gracias por tu aporte Gillermo.