Operadores de Asignación
ericknavarro/InterpreteSencilloJisonJS pull request #17
Opened 2020-01-31 23:14 UTC by AlisonLeiva

Se agregó al proyecto asignaciones donde se juntan los operadores (+,/,*,-) con el de asignación para datos de tipo numérico.

Por ejemplo:
**numero = numero + 10**;
Puede simplificarse a:
**numero += 10;**

2020-02-02 05:24 UTC, rjanixz requested changes
@AlisonLeiva tu propuesta es muy buena, solo te pido un cambio:

los operadores `+=`, `-=`, `/=`, `*=`, deben ser reconocidos desde la gramática y manejarse  desde allí como símbolos del lenguaje. Ya que la nueva producción que agregaste:

`IDENTIFICADOR operadores IGUAL expresion_numerica PTCOMA`

permite ingresar entradas como:
`x  +                         = 10`

ya que `+` y `=` son manejados como símbolos diferentes, esto puede generar conflictos en la gramática más adelante y confusión en los archivos de entrada.

Cualquier consulta, a la orden

2020-02-02 20:57 UTC, AlisonLeiva commented
@rjanixz ya fue corregido el error, cualquier cosa estaré pendiente.

2020-02-02 21:00 UTC, rjanixz approved these changes

2020-02-12 04:12 UTC, rjanixz requested changes
@AlisonLeiva hemos echo merge de otros pull requests por lo que algunos archivos han cambiado, por favor resolver los conflictos en tus archivos para proceder hacer mege.

Cualquier duda a la orden

2020-02-27 23:43 UTC, merged