Nuevo tipo de dato String
ericknavarro/InterpreteSencilloJisonJS pull request #4
Opened 2020-01-23 02:45 UTC by ronald1512

Esta es mi propuesta de mejora: agregué el tipo de dato String, ahora se pueden hacer declaraciones con este tipo, así mismo asignaciones. También realicé las validaciones correspondientes. Soy Ronald Gabriel Romero González - 201701048. Gracias por esta tarea, aprendí mucho, saludos.

2020-01-23 04:20 UTC, rjanixz commented
@ronald1512 gracias por la propuesta. Te pido por facor que quiter todos los archivos que no son necesarios, por ejemplo todos los que están dentro del directorio .folder. Es importante subir solo el los cambios en el código principal para mantener el proyecto limpio, ordenado y sea fácil de entender.

Saludos

2020-01-23 04:20 UTC, rjanixz requested changes
El PR contiene archivos innecesarios

2020-01-23 04:40 UTC, ronald1512 commented
Está bien ahora? dejé solamente los archivos necesarios

2020-01-25 15:32 UTC, rjanixz commented
Excelente trabajo @ronald1512 , un cambio final, el requerimiento dice que debes agregar comentarios descriptivos en los commits para cada archivos que cambiaste, esto es para tener mejor información de los cambios.

Para evitar los commits que hiciste quitando los archivos innecesarios:
![image](https://user-images.githubusercontent.com/6462555/73123434-8850fb00-3f55-11ea-8cd7-edfeb612630a.png)

Te recomiendo cerrar este y abrir y uno nuevo, unicamente con los archivos necesarios y poner los comentarios necesarios.

2020-01-26 03:58 UTC, closed without merging